# Generated by Django 4.2.11 on 2024-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_quickly',
            field=models.BooleanField(default=False, verbose_name='Срочный заказ?'),
        ),
    ]
