# Generated by Django 4.2.11 on 2024-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
